exclude: [LICENSE, README.md]
theme: jekyll-theme-slate
title: Michael Hoffman Tech - GitHub
url: "https://mikevoxcap.github.io"
description: "Michael Hoffman Tech - Projects and Knowledge Base"
github:
  - repository_url: https://github.com/mikevoxcap
